### ISSUE TITLE
NATS CONNECT_FAIL

### ISSUE THREAD

**Issue by atkoroma** [Kazmirchuk/nats-tcl#1]
Hi,
Thanks...I am trying out this great package.
When i run the following on the command-line, the desired outcome is achieved. However, from the script I encounter the above error. The working (command-line) script looks as follows;

```
% package require nats

% 	proc sendMsg {val1 val2 val3 val4} {
		
		set conn [nats::connection new "myConn"]
		[$conn cget -logger]::setlevel info
		$conn configure -servers nats://localhost:4222

                #command-line works without the following connection settings as well
		$conn configure -connect_timeout 200000
		$conn configure -verbose true
		$conn configure -echo false
		$conn configure -randomize false
		$conn configure -reconnect_time_wait 2000
		$conn configure -pedantic false
		$conn configure -ping_interval 120000
		$conn configure -max_outstanding_pings 2
		$conn configure -flush_interval 500
		$conn configure -tls_opts {}
		$conn configure -token {}
		$conn configure -user {}
		$conn configure -password {}
		$conn configure -connection_cb {}
		#$conn configure -name {myConn}
		$conn connect

		# create an inbox and listen for a single response
		set inbx [$conn inbox]
		$conn subscribe $inbx -callback msgResponse
				
		set subj "myconn.mysubj"
		set msgStr [binary format a* "$val1 $val2 $val3 $val4"]
		$conn publish $subj $msgStr $inbx
		vwait ::msg
		
		$conn destroy
		
		return 0
	} ;#endOf_sendMsg
	
	proc msgResponse {subj mesg replyTo} {
	
		puts "\nmsgResponse::Received\($subj $mesg $replyTo\)"
		set ::msg $mesg
	} ;#endOf_msgResponse
% 
% 
% sendMsg alie tormusa kroma male
[Mon Oct 26 08:14:16 SAST 2020] [Obj38_myConn] [info] 'Connecting to server # 0: localhost:4222'

msgResponse::Received(_INBOX.a9e69440631d5414e86d alie tormusa kroma male _INBOX.bd263888a38938cd1136.1)

msgResponse::Received(_INBOX.12b8ebb96ecadccde154 merchantTid= transId= transSubmit=2020-10-26T06:14:17Z transAmount= transStatus=INVALID_REQUEST )
% 

```
When I place the same code and execute from my script, I get the following error....

```
Error Code 'NATS CONNECT_FAIL'
    while executing
"throw {NATS CONNECT_FAIL} $config(error)"
    (class "::nats::connection" method "connect" line 24)
    invoked from within
"$conn connect"
    (procedure "sendMsg" line 24)
. . . . . .
```
Your guidance will be much appreciated...

[sendMsg.txt](https://github.com/Kazmirchuk/nats-tcl/files/5437300/sendMsg.txt)

**Comment by Kazmirchuk** [comment]
Hi!
It seems to me like you want to send just one request and get a reply, right? then you don't need to create a new inbox and subscribe to it. Just call "request" and it will return you the reply (or throw an error if nobody replied on time)
taken from your attachment:
set result [$conn request $subj $msgStr -timeout 2000]
notice that I replaced $inbx with $subj - this seems to be the main problem
There is no point to send messages to an "inbox" address, if nobody else is listening :)

**Comment by atkoroma** [comment]
Hi,

 

I was truely confused about when use an inbox or just a request...it's clear now.

Request command is quiet straight-forward.

 

However, I observed it runs fine when i place the code in a single file but I still get the same error on the connect when executed in the larger context

 

I am picking the following from the web server:

 

[Tue Oct 27 07:38:24 SAST 2020] [Obj77_yapCon] [info] 'Connecting to server # 0: localhost:4222'
Recursive VWAIT AAAARRRRRRGH! from 'type proc line 22 cmd {vwait [self object]::config(status)} method connect class ::nats::connection level 1'
1603777104599-43187mS error @@{Server Error: '1' (-errorcode {NATS CONNECT_FAIL} -errorstack {INNER {returnImm {} {-errorcode {NATS CONNECT_FAIL}}} CALL {::oo::Obj77 connect} 

. . . . .

 

If it's of any help


 

Regards,

Alie T. Koroma


 

Sent: Monday, October 26, 2020 at 7:13 PM

**Comment by Kazmirchuk** [comment]
Well, it's difficult for me to say anything about the larger context without seeing it...
"recursive vwait" is not a problem by itself, but usually points to a defect in the overall architecture.
Is the receiver of your NATS message in the same Tcl interpreter? 
Are you trying to include the NATS client into a Web server? Is it the standard "httpd" package from Tcllib? 
In any case, try using [connect] with the -async flag - this way the NATS client will not block in "vwait"
You will be notified when the client connects, if you set up a trace on $conn::config(status) or simply check it periodically:
while {[$conn cget -status] != "connected"} {
# whatever form of "sleep" is most suitable for you
}

Also I'd recommend reading the original NATS docs at nats.io to understand how publish/subscribe architectures work, reading the API [docs](https://github.com/Kazmirchuk/nats-tcl/blob/master/API.md) , and you could draw a UML sequence diagram for better understanding of how your messages are sent around.

**Comment by Kazmirchuk** [comment]
there was no reply for a while, so I'm closing this
using async versions of the API allows to avoid using vwait under the hood
