### ISSUE TITLE
"Direct get" from a stream is not really direct

### ISSUE THREAD

**Issue by Kazmirchuk** [Kazmirchuk/nats-tcl#24]
I've noticed only now that there are 2 APIs to get a message from a stream that differ when it has replicas:
1. `$JS.API.STREAM.MSG.GET.<stream>` can get a message only from a leader
2. `$JS.API.DIRECT.GET.<stream>` can get a message from any replica

Both use cases are valid depending on your requirements on read-after-write coherency. See ADR-31. In nats-py JetStreamManager.get_msg has `direct` argument that controls this.

So, either this needs to be implemented, or the API docs must be clarified.

**Comment by piotr-karas** [comment]
I have also seen it during development, but left it as-is, because I was interested in delivering something that works and then improving it as oppose to dig too much in some topic. But yes, it would be nice to have that feature and I will try to implement it soon (or at least update docs)

**Comment by Kazmirchuk** [comment]
thanks for confirmation! I can do it

btw what about moving our chat to some messenger or email? you can find me on LinkedIn

**Comment by piotr-karas** [comment]
sure, I have send you an invitation on LinkedId, but to be honest I am not using it very often, so if you want faster communication I would suggest my work email. I will send it to you on LinkedId
